version: '3.8'

services:
  mysql:
    image: mysql:5-debian
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: W3irdPassw0rd
      MYSQL_DATABASE: bookstore

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
